### ISSUE TITLE
add validators to product variants

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#249] opened 2015-03-22 21:43 UTC
preregpp.eja.net / Version: 0.2.50
I select a day ticket and a day for the ticket and assign it to a person
I go into the shopping cart
I click on "edit"
the drop down "select day" says "select select day" (low prio: why "select select" twice?)
after "save changes" the day for the day ticket is lost

**Comment by smadamit** [comment] 2015-03-22 22:03
I can not reproduce this error, but have two more issues, so I guess there is some work left:
- I can put in a day ticket with the option "select day" -> productVariantValue = NULL
- if I am in card and click edit to a day ticket the default option of the select is "select select day". Should be the day which is currently set in database.

**Comment by smadamit** [comment] 2015-03-22 22:07
Ah I think Christians issue is exactly mine (first one). We both mean the same.

**Comment by inbaz** [comment] 2015-03-23 07:49
The value is lost because of the field description "select day", the space is the problem. 0.2.51 can handle spaces in variant names.

The two select is the problem of the first field in this dropdown: 'label' => 'select '.$variant->getName() I put a select in front of the variant name. So here the variant name is select day. What do we want here? Simply the name of the variant in the first field or the variant name to be just "Day"? In the shopping cart for this name the line would be:

 Day Ticket ( select day: August 4 (Tuesday) ) 

Looks strange, too. I would suggest to cut off the select here.

**Comment by smadamit** [comment] 2015-03-23 10:32
tested in 0.2.51

- edit gala show -> preselected option is the value from database -> **it works**
- rename "'select '.$variant->getName()" just to "". An empty option.
- I can put in a day ticket with the option "select day" -> productVariantValue = NULL -> **please fix it**

**Comment by smadamit** [comment] 2015-03-23 16:47
see also: #258

**Comment by inbaz** [comment] 2015-03-23 18:39
I think null can be still selected, because the validators for variants are not implemented, yet. The rest should be fixed in 0.2.55.

**Comment by smadamit** [comment] 2015-03-24 19:59
duplicate to #258

**Comment by inbaz** [comment] 2015-03-25 09:16
added validator for product variant values

**Comment by smadamit** [comment] 2015-03-25 12:10
tested in 0.2.64 -> OK

**Closed** 2015-03-25 12:09 UTC
Labels: bug, prio1, retest
