### ISSUE TITLE
Handling of duplicate mail addresses

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#178] opened 2015-03-13 21:59 UTC
Current issue:
* A person was created
* Click on "My persons"
* Edit person
* Change e.g. the last name

==> The changes can't be saved without also altering the mail adress because "There is already a person with this email address in your order" (seems that the result of the edit is evaluated against the current state of the person).

On a broader note: Do we need to make sure that each participant enters a different mail adress? Personally, I'd argue that it is not necessary:
* Families might want to check in their children on their parents mail address
* Youth circus groups might want to register everyone on the same address

In my opinion, removing the restriction gives the greatest flexibility. People can still enter a different address per participant, but they are not forced to jump hoops if they don't want to.

**Comment by smadamit** [comment] 2015-03-13 22:16
For now it's a workaround. In the end existing accounts should be used by log in for new orders, changes...

Note: email field is optional and generates an user account.

This particular issue is a bug.

**Comment by smadamit** [comment] 2015-03-13 22:21
similar to #135

**Comment by inbaz** [comment] 2015-03-14 15:37
fixed in 0.2.34

**Comment by philip-n** [comment] 2015-03-14 21:09
Tested in 0.2.34, works.

**Comment by jackcaveman** [comment] 2015-03-15 14:46
You can't add multiple participants with the same email address (I have not yet selected a purchaser). I agree with Philip that this is not expected behavior is you are ordering for a family with 5 children.

What was decided on this issue?

**Comment by inbaz** [comment] 2015-03-15 20:23
The initial issue was that an already existing person can't be changed anymore, because the system found a participant with that email address. That was fixed.

Since the email is optional you do not need to add an email address to each participant. At the choose purchaser page is the hint that the purchaser gets all eTickets and every participant who has an email address set will get his/her eTicket, too.

In my opinion there is no todo. If we need the explanation for that anywhere else just tell me where you would expect it.

**Comment by smadamit** [comment] 2015-03-16 13:27
Maybe we need a general explanation for the users, how the order is working. Jasper do you have a suggestion for that. From the coding point of view there is no todo.

Short note next to the email field: "If you enter an email address to this person all his/her etickets will be sent directly to him/her... All etickets will also be send to purchaser..."

**Comment by jackcaveman** [comment] 2015-03-16 18:49
My suggestion is in similar lines, although the optional gives it away:
"E-ticket(s) are send directly to this person's email. To receive the
eticket(s) on your own email address, leave it blank".

**Comment by smadamit** [comment] 2015-03-17 08:59
The purchaser will get all etickets, also these ones which are directly send to a person.

**Comment by smadamit** [comment] 2015-03-17 18:00
I close this and open a new issue: #199

**Closed by smadamit** 2015-03-17 18:00 UTC
Labels: bug, prio1
