### ISSUE TITLE
German text in checkout confirmation on "terms and conditions"

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#121] opened 2015-03-08 22:29 UTC
Version 0.2.23
In the tickbox to accept "terms and conditions" the text "aktivieren sie dieses Kontrollkästchen, wenn sie fortfahren wollen" appears. This is strange. All other text is in English, only this one in German.
Is it possible to be consistent, i.e. change this text to English?

**Comment by inbaz** [comment] 2015-03-09 09:08
A quick view on this issue shows that this message does not come from the system but from the browser itself. I'll look deeper into it when other important issues are fixed. I think this is no show stopper, or not?

**Comment by smadamit** [comment] 2015-03-09 10:33
I think you are right. In that case I would close the issue since this is OK. If you have selected German as your language in the browser settings and the browser speaks German to you that's not a bug, it's a feature.

**Closed by smadamit** 2015-03-09 10:33 UTC
Labels: prio1, Text
